### ISSUE TITLE
are the y-points correct? problems validating ietf-cose-msg examples

### ISSUE THREAD

**Issue by mcr** [DavidEGrayson/ruby_ecdsa#9]
Background: I am writing some code to implement the IETF COSE specification (here: https://datatracker.ietf.org/doc/draft-ietf-cose-msg/ about to be RFC). The examples from Jim are at: https://github.com/cose-wg/Examples . I am actually implementing a CWT library in ruby ( https://datatracker.ietf.org/doc/draft-ietf-ace-cbor-web-token/  ) for use in the ANIMA and 6tisch WG, if you care.
My code, which is still a skeletal mess at: git@github.com:mcr/ChariWTs.git is just trying to use the ecdsa libraries to validate the examples.  There are a few challenges here, which you can read more about at: https://github.com/cose-wg/Examples/issues/79

So I took the two ecdsa examples: https://github.com/cose-wg/Examples/blob/master/ecdsa-examples/ecdsa-sig-01.json and https://github.com/cose-wg/Examples/blob/master/ecdsa-examples/ecdsa-sig-02.json
and I did ran some really simple ruby code to re-derive the x/y coordinates (the public key) from the d value presented:

~~~~~~~~
2.3.0 :004 > load 'check1.rb'
derived x: 84479481090508879236361810314595438639920637850206250382769291656310074416895 
       vs: 84479481090508879236361810314595438639920637850206250382769291656310074416895
derived y: 14508547282523033594077281899984253063221771617900828323772342424228169781630 
       vs: 221382765198319077083920120796396551052321440967416757858684904626210296
~~~~~~~~

Here is the shortest code: https://gist.github.com/mcr/b1c9dd9cfcab249e73200d0d056ac0da to attempt to validate this.  That the *X* matches is surprising if there is numerically wrong.  My hunch is that there is some problem with Jim's examples that is corrupting the Y value coming out.

**Comment by DavidEGrayson** [comment]
My first thought was that maybe the private key was negated, because if you negate the private key (and take it module the order of the group) then the Y coordinate changes buy the X coordinate stays the same.  That theory did not check out.

The next thing I tried to do was to print your coordinates in HEX, and that was a little more revealing.  I got:

```
derived x: 0xbac5b11cad8f99f9c72b05cf4b9e26d244dc189f745228255a219a86d6a09eff
       vs: 0xbac5b11cad8f99f9c72b05cf4b9e26d244dc189f745228255a219a86d6a09eff
derived y: 0x20138bf82dc1b6d562be0fa54ab7804a3a64b6d72ccfed6b6fb6ed28bbfc117e
       vs: 0x20138b0b706db558af8254ab7804a3a64b6d72ccf5adbedbb4a2eff045f8
```

See how the derived y and the and the expected y start with the same 6 HEX digits?  That makes me think that there was a typo in the Base64-encoded number, or some digits were omitted.  Also, the Base64-decoded Y coordinate is improbably small compared to the group order, which makes me think again that some digits were omitted by accident in that example.

**Comment by mcr** [comment]
David Grayson <notifications@github.com> wrote:
    > My first thought was that maybe the private key was negated, because
    > if you negate the private key (and take it module the order of the
    > group) then the Y coordinate changes buy the X coordinate stays the
    > same. That theory did not check out.

    > The next thing I tried to do was to print your coordinates in HEX, and
    > that was a little more revealing. I got:

    > derived x: 0xbac5b11cad8f99f9c72b05cf4b9e26d244dc189f745228255a219a86d6a09eff
    > vs: 0xbac5b11cad8f99f9c72b05cf4b9e26d244dc189f745228255a219a86d6a09eff
    > derived y: 0x20138bf82dc1b6d562be0fa54ab7804a3a64b6d72ccfed6b6fb6ed28bbfc117e
    > vs: 0x20138b0b706db558af8254ab7804a3a64b6d72ccf5adbedbb4a2eff045f8

    > See how the derived y and the and the expected y start with the same 6
    > HEX digits? That makes me think that there was a typo in the

I was also thinking this.  The -01 example has the - in the base64, and I
wondered if that might be wrong in some way, but the -02 example has no such
things, and I get the same thing.

I was meaning to write it out in binary and see if maybe there are some
sequences of 0s in the middle that would line things up.



--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by mcr** [comment]
The base64 decoder is at fault.
The strict_base64 decode (the default), throws away the "-" which are really base64url charset.
Using urlsafe_decode64() treats the input correctly, and the y-values line up perfectly.
